monthly_income = float(input("Enter your monthly income: "))
monthly_expense = float(input("Enter your total monthly expenses: "))
Monthly_Savings = monthly_income - monthly_expense ; float(monthly_income) - float(monthly_expense)
print("Your montly savings are", Monthly_Savings)
Projected_Savings = (Monthly_Savings * 12 + (Monthly_Savings * 12 * 0.05))
print("Projected savings after one year, with interest, is:", Projected_Savings)
